default:
  - 'connect'
  - 'open'
  - 'esteWatch'

init:
  - 'bower:install'

hint:
  - 'jshint'

build:
  - "sass:compile"
  - "notify:sass"

distcheck:
  - 'useminPrepare'

dist:
  - "sass:dist"
  - "useminPrepare"
  - "concat"
  - "uglify"
  - "usemin"
  - "clean"
